//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsClass
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int ClassID { get; set; }
    }
}
